version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "shopping-cart-303"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-xxxxxxxxxxxx"
s3_prefix = "shopping-cart-303"
region = "us-east-2"
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
parameter_overrides = "Environment=\"dev\""
image_repositories = []
