AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Cognito Resources for Todo Application

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, staging, prod]
    Description: Deployment environment

Resources:
  # Cognito User Pool
  TodoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub ${Environment}-todo-user-pool
      AutoVerifiedAttributes:
        - email
      Schema:
        - Name: email
          AttributeDataType: String
          Required: true
          Mutable: true
        - Name: name
          AttributeDataType: String
          Required: true
          Mutable: true
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
      MfaConfiguration: OPTIONAL
      EmailVerificationSubject: 'Your verification code'
      EmailVerificationMessage: 'Your verification code is {####}'
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: false

  # Cognito User Pool Client
  TodoWebClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub ${Environment}-todo-web-client
      UserPoolId: !Ref TodoUserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      PreventUserExistenceErrors: ENABLED
      SupportedIdentityProviders:
        - COGNITO

  # Cognito Identity Pool
  TodoIdentityPool:
    Type: AWS::Cognito::IdentityPool
    Properties:
      IdentityPoolName: !Sub ${Environment}-todo-identity-pool
      AllowUnauthenticatedIdentities: false
      CognitoIdentityProviders:
        - ClientId: !Ref TodoWebClient
          ProviderName: !Sub cognito-idp.${AWS::Region}.amazonaws.com/${TodoUserPool}

  # IAM Roles for Identity Pool
  AuthenticatedRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${Environment}-todo-authenticated-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: cognito-identity.amazonaws.com
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                cognito-identity.amazonaws.com:aud: !Ref TodoIdentityPool
              ForAnyValue:StringLike:
                cognito-identity.amazonaws.com:amr: authenticated
      Policies:
        - PolicyName: AuthenticatedAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - mobileanalytics:PutEvents
                  - cognito-sync:*
                  - cognito-identity:*
                Resource: '*'
              - Effect: Allow
                Action:
                  - execute-api:Invoke
                Resource: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:*/${Environment}/*

  # Identity Pool Role Attachment
  IdentityPoolRoleAttachment:
    Type: AWS::Cognito::IdentityPoolRoleAttachment
    Properties:
      IdentityPoolId: !Ref TodoIdentityPool
      Roles:
        authenticated: !GetAtt AuthenticatedRole.Arn

Outputs:
  UserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref TodoUserPool
    Export:
      Name: !Sub ${Environment}-cognito-stack-UserPoolId
  UserPoolArn:
    Description: Cognito User Pool ARN
    Value: !GetAtt TodoUserPool.Arn
    Export:
      Name: !Sub ${Environment}-cognito-stack-UserPoolArn
  UserPoolClientId:
    Description: Cognito User Pool Client ID
    Value: !Ref TodoWebClient
    Export:
      Name: !Sub ${Environment}-cognito-stack-UserPoolClientId
  IdentityPoolId:
    Description: Cognito Identity Pool ID
    Value: !Ref TodoIdentityPool
    Export:
      Name: !Sub ${Environment}-cognito-stack-IdentityPoolId
  AuthenticatedRoleArn:
    Description: IAM Role ARN for authenticated users
    Value: !GetAtt AuthenticatedRole.Arn
    Export:
      Name: !Sub ${Environment}-cognito-stack-AuthenticatedRoleArn
