version = 0.1

[default.deploy.parameters]
stack_name = "airline-302"
resolve_s3 = true
s3_prefix = "airline-302"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev\""
image_repositories = []
