AWSTemplateFormatVersion: '2010-09-09'
Description: Cognito User Pool for shopping cart application

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
    Description: Deployment environment

Resources:
  ShoppingCartUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub ${Environment}-shopping-cart-user-pool
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
      Schema:
        - Name: email
          AttributeDataType: String
          Mutable: true
          Required: true
        - Name: username
          AttributeDataType: String
          Mutable: true
          Required: true
      EmailConfiguration:
        EmailSendingAccount: COGNITO_DEFAULT

  ShoppingCartUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub ${Environment}-shopping-cart-web-client
      UserPoolId: !Ref ShoppingCartUserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      SupportedIdentityProviders:
        - COGNITO
      CallbackURLs:
        - http://localhost:3000
        - https://example.com
      LogoutURLs:
        - http://localhost:3000
        - https://example.com
      AllowedOAuthFlows:
        - code
        - implicit
      AllowedOAuthScopes:
        - phone
        - email
        - openid
        - profile
        - aws.cognito.signin.user.admin
      AllowedOAuthFlowsUserPoolClient: true

Outputs:
  UserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref ShoppingCartUserPool
    Export:
      Name: !Sub ${Environment}-ShoppingCartUserPoolId

  UserPoolClientId:
    Description: Cognito User Pool Client ID
    Value: !Ref ShoppingCartUserPoolClient
    Export:
      Name: !Sub ${Environment}-ShoppingCartUserPoolClientId
